name: 问题报告 / Bug Report
description: 报告插件存在的问题
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你提交问题！请尽量填写完整信息以便快速定位问题。

  - type: input
    id: ha_version
    attributes:
      label: Home Assistant 版本
      placeholder: "例如: 2024.12.0"
    validations:
      required: true

  - type: input
    id: integration_version
    attributes:
      label: 插件版本
      placeholder: "例如: 1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 请详细描述遇到的问题
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 错误日志
      description: 请粘贴 HA 日志中与本插件相关的错误信息
      render: text

  - type: textarea
    id: expected
    attributes:
      label: 期望的行为
      description: 你期望插件应该如何工作？
